### ISSUE TITLE
Why does robot top gameobject have ridigbody?

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#82]
We should discuss this.

**Comment by bjorntore** [comment]
Remember hearing somewhere that any object you plan to move that contains a
collider should also have a ridigbody. I'd not the
collider-physics-data-something has to be recalculated all the time.

Haven't founs a solid source now googling on my phone, this was the
closest:
http://answers.unity3d.com/questions/11324/move-gameobject-with-collider-without-rigidbody-co.html

Tick the "is kinematic" box if I haven't done that, since we are moving the
transform directly, not using physics.

**Comment by Andrioden** [comment]
Seemsgood
